const AUTH_LOGIN = 'AUTH_LOGIN'
const AUTH_LOGOUT = 'AUTH_LOGOUT'
const ADD_NEWS = 'ADD_NEWS'
const APPROVE_NEWS = 'APPROVE_NEWS'
const DELETE_NEWS = 'DELETE_NEWS'
const SEARCH_NEWS = 'SEARCH_NEWS'

export {
  AUTH_LOGIN,
  AUTH_LOGOUT,
  ADD_NEWS,
  APPROVE_NEWS,
  DELETE_NEWS,
  SEARCH_NEWS
}
