const USER_COME = 'USER_COME'
const LOG_IN = 'LOG_IN'
const ADD_NEWS = 'ADD_NEWS'
const APPROVE_NEWS = 'APPROVE_NEWS'
const DELETE_NEWS = 'DELETE_NEWS'
const SEARCH_NEWS = 'SEARCH_NEWS'

export { USER_COME, LOG_IN, ADD_NEWS, APPROVE_NEWS, DELETE_NEWS, SEARCH_NEWS }
